### ISSUE TITLE
Event: "Force booking" 

### ISSUE THREAD

**Issue by BeMyTv** [Intermezzon/palms.academy#70] opened 2024-06-07 07:51 UTC
If you want to book a person for an event after the registration deadline has passed, they end up in a "waiting" state. The same applies if you want to book someone who doesn’t meet the prerequisites or who has participated in the event previously. To move the user from the waiting state to the actual event, priority must be given.

Currently, only SuperUsers can "Forsce booking"  
It would be desirable to lower this level to, for example, content administrators or add additional settings for managing events. This way, administrators of events wouldn’t have to have all the remaining permissions that a superuser has, such as global statistical rights."

**Comment by onnerby** [comment] 2024-06-10 07:44
Related to #48

**Comment by onnerby** [comment] 2024-06-10 07:46
Duplicate of #27

**Closed as completed by onnerby** 2024-06-10 07:46 UTC
Labels: type: Enhancement, module: Event
